
work_path: '/var/lib/savedata'

logging:
      mode : 'on'
      path : '/var/log/savedata'

#email:
#      smtp_settings:
#          username: 'from@example.com'
#          password: 'xxx'
#          address: 'smtp.yandex.ru'
#          port: 587
#      from: 'from@example.com'
#      to: 'to@example.com'
#      send_succes: true
#      send_failed: true


